# Generated by Django 4.1.7 on 2023-03-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_language', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='functioninfo',
            name='arguments',
        ),
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_function_type', models.CharField(max_length=64)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funkdata.language')),
            ],
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='function_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.functiontype'),
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.language'),
        ),
    ]
