# Generated by Django 4.1.7 on 2023-03-08 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0002_language_remove_functioninfo_arguments_functiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntax', models.CharField(max_length=64)),
                ('parameters', models.CharField(max_length=64)),
                ('return_value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=64)),
                ('function_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.functiontype')),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.language')),
            ],
        ),
        migrations.DeleteModel(
            name='FunctionInfo',
        ),
        migrations.AddField(
            model_name='functiondata',
            name='function_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.functionname'),
        ),
    ]
