# Generated by Django 4.1.7 on 2023-03-08 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0003_functiondata_functionname_delete_functioninfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntax', models.CharField(max_length=64)),
                ('parameters', models.CharField(max_length=64)),
                ('return_value', models.CharField(max_length=64)),
                ('function_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.functionname')),
                ('function_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.functiontype')),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funkdata.language')),
            ],
        ),
    ]
