# Generated by Django 4.1.7 on 2023-03-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0004_functionall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionname',
            old_name='function_name',
            new_name='unique_function_name',
        ),
        migrations.AlterField(
            model_name='language',
            name='unique_language',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
