# Generated by Django 4.1.7 on 2023-03-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0005_rename_function_name_functionname_unique_function_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontype',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funkdata.language', unique=True),
        ),
    ]
