# Generated by Django 4.1.7 on 2023-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0006_alter_functiontype_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionname',
            name='unique_function_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
