# Generated by Django 4.1.7 on 2023-03-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0007_alter_functionname_unique_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontype',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funkdata.language'),
        ),
        migrations.AlterField(
            model_name='functiontype',
            name='unique_function_type',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
