# Generated by Django 4.1.7 on 2023-03-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0008_alter_functiontype_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionall',
            name='syntax',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
