# Generated by Django 4.1.7 on 2023-03-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0009_alter_functionall_syntax'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='functiontype',
            unique_together={('language', 'unique_function_type')},
        ),
    ]
