# Generated by Django 4.1.7 on 2023-03-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0010_alter_functiontype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontype',
            name='unique_function_type',
            field=models.CharField(max_length=64),
        ),
    ]
