# Generated by Django 4.1.7 on 2023-03-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0012_alter_functionall_syntax_delete_functiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionall',
            name='syntax',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
