# Generated by Django 4.1.7 on 2023-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funkdata', '0013_alter_functionall_syntax'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionall',
            name='example',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionall',
            name='misc',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
